--Trigger Functions-
--ADDED UPDATE_DATE and UPDATED_BY_USER to table PET_CARE_LOG--

--CREATE TABLES--
CREATE TABLE PET_CARE_LOG (
    PRODUCT_ID NUMBER,
    LOG_DATETIME TIMESTAMP,
    CARE_INSTRUCTIONS VARCHAR2(1000),
    UPDATE_DATE DATE,              
    UPDATED_BY_USER VARCHAR2(100), 
    PRIMARY KEY (PRODUCT_ID, LOG_DATETIME),
    CONSTRAINT fk_petcare_product FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE SALE_ITEM (
    SALES_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER DEFAULT 1,
    PRIMARY KEY (SALES_ID, PRODUCT_ID),
    CONSTRAINT fk_saleitem_sale FOREIGN KEY (SALES_ID) REFERENCES CUSTOMER_SALE(SALES_ID),
    CONSTRAINT fk_saleitem_product FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE CUSTOMER_SALE (
    SALES_ID NUMBER PRIMARY KEY,
    CUST_ID NUMBER NOT NULL,
    SALE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT fk_sale_customer FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100),
    PRODUCT_DESCRIPTION VARCHAR2(255),
    PARENT_PRODUCT_ID NUMBER, 
    CONSTRAINT fk_product_package FOREIGN KEY (PARENT_PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE CUSTOMER (
    CUST_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100),
    ADDRESS VARCHAR2(255)
);



--INSERT TRIGGER--

CREATE OR REPLACE TRIGGER trg_pet_care_insert
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.UPDATE_DATE := SYSDATE;
    :NEW.UPDATED_BY_USER := USER;
    
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'An error occurred during insert into PET_CARE_LOG: ' || SQLERRM);
END;
/

--UPDATE TRIGGER--

CREATE OR REPLACE TRIGGER trg_pet_care_update
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != :OLD.UPDATED_BY_USER THEN
        RAISE_APPLICATION_ERROR(-20002, 'Update failed: You are only allowed to update records that you created.');
    END IF;

    :NEW.UPDATE_DATE := SYSDATE;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-20002) 
            RAISE_APPLICATION_ERROR(-20003, 'An error occurred during update on PET_CARE_LOG: ' || SQLERRM);
        ELSE
            RAISE; 
        END IF;
END;
/


--DELETE TRIGGER--

CREATE OR REPLACE TRIGGER trg_pet_care_delete
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(-20004, 'Delete failed: Only the manager (JOEMANAGER) is authorized to delete records.');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-20004) THEN
            RAISE_APPLICATION_ERROR(-20005, 'An error occurred during delete on PET_CARE_LOG: ' || SQLERRM);
        ELSE
            RAISE; 
        END IF;
END;
/